
kind: pipeline
name: node14

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: install
  image: node:14
  commands:
  - npm install

- name: build
  image: node:14
  commands:
  - make build

- name: test
  image: node:14
  commands:
  - make test.ci

- name: codecov
  image: node:14
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
  - make upload.codecov

volumes:
  - name: cache
    host:
      path: /tmp/cache
