
kind: pipeline
name: node14

steps:
- name: install
  image: node:14
  commands:
  - npm install
- name: build
  image: node:14
  commands:
  - make build
- name: test
  image: node:14
  commands:
  - make test.ci
- name: codecov
  image: node:14
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
  - make upload.codecov
