# This is a basic workflow that is manually triggered

name: Create Tag

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version to bump
        options: 
        - patch
        - minor
        - major
        default: 'patch'
      commit:
        description: 'Commit to target tag'
        default: 'HEAD'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  bump_version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Show input
      run: echo "Hello ${{ inputs.commit }}, branch ${{ github.ref }}, version ${{ inputs.version }}"
    
    - uses: actions/checkout@v3
    - run: git config push.default current && git config pull.default current && git pull --tags

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    # - run: npm version patch
    # - run: git push --tags
    # - run: git push origin/master
