
name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version to bump
        options: 
        - patch
        - minor
        - major
        default: 'patch'

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git config push.default current
        git config pull.default current
    
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: git pull --tags
    - run: npm version ${{ inputs.version }}
    - run: git push --tags
    - run: git push
