# This is a basic workflow that is manually triggered

name: Create Tag

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commit:
        description: 'Commit to target tag'
        default: 'HEAD'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  bump_version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Show input
      run: echo "Hello ${{ inputs.commit }}, branch ${{ github.ref }}, GITHUB_BASE_REF ${{ vars.GITHUB_BASE_REF }}"
    
    - uses: actions/checkout@v3
    - run: git config push.default current && git config pull.default current && git pull --tags

    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm --version

    # - run: git push --tags
    # - run: git push origin/master
